#!/usr/bin/env bash
# Builds CAL — the ObjC++ bridge layer. Prefers swift build when no Xcode
# project exists (none is generated by default in this repo).
set -euo pipefail

cd "$(dirname "$0")/.."

if [ ! -d build/Sephrium.framework ]; then
    echo "[sephr] build/Sephrium.framework missing — run build_sephrium.sh first"
    exit 1
fi

if [ -f cal/CAL.xcodeproj/project.pbxproj ]; then
    xcodebuild \
        -project cal/CAL.xcodeproj \
        -scheme CAL \
        -destination "generic/platform=macOS" \
        -configuration Release \
        -derivedDataPath build/DerivedData \
        archive -archivePath build/CAL.xcarchive SKIP_INSTALL=NO
    xcodebuild -create-xcframework \
        -framework build/CAL.xcarchive/Products/Library/Frameworks/CAL.framework \
        -output build/CAL.xcframework
    echo "[sephr] CAL.xcframework → $(pwd)/build/CAL.xcframework"
else
    # SPM path — CAL builds as a library target that Sephr links.
    swift build --product CAL -c release
    echo "[sephr] CAL built via SPM → $(pwd)/.build/release/libCAL.a"
fi
